import {
  BadgeCheck,
  Building2,
  ClipboardCheck,
  Database,
  FileInput,
  FileText,
  Gauge,
  History,
  Hospital,
  Languages,
  Paperclip,
  Pill,
  RotateCcw,
  Stethoscope,
} from "lucide-react";

export const menuSections = [
  {
    id: "dashboard",
    title: "ダッシュボード",
    icon: Gauge,
    list: "Portfolio Dashboard",
    description: "複数の治験届、マスタ変更、届出期限候補、リマインダーを横断管理します。",
    mode: "dashboard",
  },
  {
    id: "masters",
    title: "マスタ管理",
    icon: Database,
    list: "Master Data",
    description: "医師、治験薬、治験使用薬、医療機関、IRB、添付資料、届出者の常時変更情報を管理します。",
    mode: "masterDashboard",
  },
  {
    id: "import",
    title: "既存PDF取込",
    icon: FileInput,
    list: "PDF Import & Versioning",
    description: "既存の治験届PDFを取り込み、構造化して次回変更届のベースにします。",
    mode: "import",
  },
  {
    id: "overview",
    title: "届出概要",
    icon: FileText,
    list: "CTN Submissions",
    description: "届出種別、届出区分、受付番号、初回届情報を管理します。30日調査はこの画面では扱いません。",
    fields: [
      { key: "trialCode", label: "治験識別記号", required: true, xsd: "TESTSUBSTANCEIDCODE" },
      { key: "submissionType", label: "届出種別", required: true, type: "select", options: ["治験計画届", "治験計画変更届", "治験中止届", "治験終了届", "開発中止届"] },
      { key: "changeCategory", label: "届出区分", required: true, type: "select", options: ["区分1", "区分2", "区分3", "対象外"] },
      { key: "submissionRound", label: "届出回数", required: true, type: "number", xsd: "SERIALNOTENUM" },
      { key: "initialReceiptNo", label: "初回届受付番号", required: true, xsd: "RECEPTNUMINITNOTE" },
      { key: "initialDate", label: "初回届年月日", required: true, type: "date", xsd: "INITNOTEDATE" },
      { key: "plannedStartDate", label: "治験開始予定日", required: true, type: "date" },
      { key: "submissionDueDate", label: "提出期限", required: false, type: "date" },
    ],
  },
  {
    id: "termination",
    title: "中止情報",
    icon: ClipboardCheck,
    list: "Premature Termination",
    description: "B.3.6の中止年月日、中止理由、その後の対応を入力します。中止届・開発中止届で使用します。",
    fields: [
      { key: "terminationDate", label: "中止年月日", required: false, type: "date", xsd: "TERMINATIONDATE", limit: 8 },
      { key: "reasonTermination", label: "中止理由", required: false, type: "textarea", xsd: "REASONTERMINATION", limit: 1000 },
      { key: "postTerminationMeasure", label: "その後の対応", required: false, type: "textarea", xsd: "POSTTERMINATIONMEASURE", limit: 1000 },
    ],
  },
  {
    id: "protocol",
    title: "治験計画",
    icon: ClipboardCheck,
    list: "Protocol Summaries",
    description: "実施計画書、相、目的、対象疾患、用法用量、期間を入力します。",
    fields: [
      { key: "protocolNo", label: "実施計画書番号", required: true, xsd: "PROTOCOLNUM" },
      { key: "phase", label: "開発の相", required: true, type: "select", options: ["第I相", "第II相", "第III相", "製造販売後"], xsd: "PHASECLINTRIAL" },
      { key: "trialType", label: "試験の種類", required: true, xsd: "TYPECLINTRIAL" },
      { key: "targetDisease", label: "対象疾患", required: true, xsd: "TARGETDISEASE" },
      { key: "plannedSubjectsTotal", label: "予定被験者数 合計", required: true, type: "number", xsd: "PLANNUMSUBJECTSTOTAL" },
      { key: "objectives", label: "目的", required: true, type: "textarea", xsd: "TRIALOBJECTIVES" },
      { key: "dosageAdmin", label: "用法及び用量", required: true, type: "textarea", xsd: "DOSAGEADMIN" },
    ],
  },
  {
    id: "primaryProduct",
    title: "被験薬・治験使用薬",
    icon: Pill,
    list: "Primary / Investigational Products",
    description: "主たる被験薬と治験使用薬を同一セクションで入力します。投与経路・剤形などはコード選択の補助を表示します。",
    fields: [
      { key: "sponsorName", label: "製造所又は営業所 名称", required: false, xsd: "SPONSOR_NAME", limit: 100 },
      { key: "sponsorAddress1", label: "製造所又は営業所 所在地1", required: false, xsd: "SPONSOR_ADDRESS1", limit: 120 },
      { key: "sponsorAddress2", label: "製造所又は営業所 所在地2", required: false, xsd: "SPONSOR_ADDRESS2", limit: 120 },
      { key: "manufacturerImporterCode", label: "業者コード", required: false, xsd: "MANUFACTURERIMPORTERCODE", limit: 9 },
      { key: "ingredientsQuantities", label: "成分及び分量", required: false, type: "textarea", xsd: "INGREDIENTSQUANTITIES" },
      { key: "dosageFormCode", label: "剤形コード", required: false, xsd: "DOSAGEFORMCODE", limit: 2 },
      { key: "manufactMethod", label: "製造方法", required: false, type: "textarea", xsd: "MANUFACTMETHOD" },
      { key: "intendIndicationsEffects", label: "予定される効能又は効果", required: false, type: "textarea", xsd: "INTENDINDICATIONSEFFECTS", limit: 1024 },
      { key: "efficacyClassCodeNumber", label: "薬効分類番号", required: false, xsd: "EFFICACYCLASSCODENUMBER", limit: 3 },
      { key: "intendDosageAdmin", label: "予定される用法及び用量", required: false, type: "textarea", xsd: "INTENDDOSAGEADMIN", limit: 1024 },
      { key: "adminRouteCode", label: "投与経路コード", required: false, xsd: "ADMINROUTECODE", limit: 2 },
    ],
    mode: "productEntry",
  },
  {
    id: "chargeOutPersons",
    title: "費用負担者",
    icon: Building2,
    list: "Charge Out Persons",
    description: "B.3.12.10の費用負担者を複数行で管理します。",
    mode: "chargeOutTable",
  },
  {
    id: "coordinatingDoctors",
    title: "治験調整医師",
    icon: Stethoscope,
    list: "Coordinating Investigators",
    description: "B.3.12.11の治験調整医師を複数行で管理し、外字と所属を確認します。",
    mode: "coordinatingDoctorTable",
  },
  {
    id: "cros",
    title: "CRO",
    icon: Building2,
    list: "Contract Research Organizations",
    description: "B.3.12.12のCRO名称、所在地、委託業務を複数行で管理します。",
    mode: "croTable",
  },
  {
    id: "combination",
    title: "併用製品等",
    icon: RotateCcw,
    list: "Combination Products",
    description: "B.4の治験使用薬、治験使用機器相当、治験使用製品相当を複数行で管理します。",
    mode: "combinationTable",
  },
  {
    id: "institutions",
    title: "医療機関情報",
    icon: Hospital,
    list: "Medical Institutions",
    description: "施設単位の情報を順序番号付きで管理し、医師・IRB・SMO・数量を配下に持ちます。",
    mode: "institutionTable",
  },
  {
    id: "siteGovernance",
    title: "施設別SMO・IRB",
    icon: Hospital,
    list: "Site SMO / IRB",
    description: "B.5.1.k.12〜B.5.1.k.13の医療機関ごとのSMOとIRB情報を入力します。",
    mode: "siteGovernance",
  },
  {
    id: "otherInfo",
    title: "その他情報",
    icon: ClipboardCheck,
    list: "Other Information",
    description: "カルタヘナ法、生物由来製品、コンパニオン診断薬、国際共同治験、遺伝子検査等の該当性を入力し、ロジックチェックします。",
    fields: [
      { key: "cartagenaType", label: "カルタヘナ法対象薬物の該当性", required: false, type: "select", options: ["該当なし", "第一種", "第二種", "第一種及び第二種"], xsd: "TYPECLINTRIALWITHDRUGCARTAGENA", limit: 20 },
      { key: "cartagenaDetail", label: "該当する場合の詳細", required: false, type: "textarea", xsd: "DETAIL", limit: 2000 },
      { key: "biologicalProductType", label: "生物由来製品の該当性", required: false, type: "select", options: ["該当なし", "生物由来製品（承認済）", "生物由来製品（指定済）", "特定生物由来製品（承認済）", "特定生物由来製品（指定済）"], xsd: "TYPEBIOLOGICALPROD", limit: 20 },
      { key: "codxApplicable", label: "コンパニオン診断薬等の開発", required: false, type: "select", options: ["該当なし", "該当あり"], xsd: "INFORESEARCHFORCODX" },
      { key: "combinationProdApplicable", label: "コンビネーション製品に関する治験", required: false, type: "select", options: ["該当なし", "該当あり"], xsd: "INFOCLINTRIALFORCOMBINATIONPROD" },
      { key: "expandedAccessType", label: "拡大治験の位置付け", required: false, type: "select", options: ["該当なし", "拡大治験", "主たる治験"], xsd: "TYPEEXPANDEDACCESSPROG", limit: 20 },
      { key: "globalTrial", label: "国際共同治験", required: false, type: "select", options: ["該当なし", "該当あり"], xsd: "INFOGLOBALCLINTRIAL" },
      { key: "globalTrialContents", label: "国際共同治験 内容", required: false, type: "textarea", xsd: "CONTENTS", limit: 1024 },
      { key: "geneTestIncluded", label: "ゲノム検査等を含む治験", required: false, type: "select", options: ["該当なし", "該当あり"], xsd: "INFOCLINTRIALINCLUDINGGENETEST" },
      { key: "microdoseClinicalTrial", label: "マイクロドーズ臨床試験を利用した開発", required: false, type: "select", options: ["該当なし", "該当あり"], xsd: "INFOPRODUSINGMDCLINTRIAL" },
      { key: "equipmentContents", label: "併用する機械器具等の記載", required: false, type: "textarea", xsd: "INFOCOMBEQUIPMENT", limit: 2000 },
      { key: "otherCommentsProtocol", label: "当該届出に関するその他", required: false, type: "textarea", xsd: "OTHERCOMMENTS_PROTOCOL", limit: 1024 },
    ],
  },
  {
    id: "documents",
    title: "添付資料・備考",
    icon: Paperclip,
    list: "Documents & Remarks",
    description: "B.3.15〜B.3.16の備考、添付資料名、添付資料備考を管理します。",
    mode: "documentsTable",
  },
  {
    id: "applicant",
    title: "届出者・海外依頼者",
    icon: Building2,
    list: "Applicant / Foreign Sponsor",
    description: "B.3.17〜B.3.18の届出者、担当者、海外依頼者又は外国製造業者を入力します。",
    fields: [
      { key: "classPersonFillNote", label: "治験届出者の種別", required: false, type: "select", options: ["治験依頼者", "自ら治験を実施する者"], xsd: "CLASSPERSONFILLNOTE", limit: 50 },
      { key: "applicantName", label: "届出者 名称", required: false, xsd: "APPLICAT_NAME", limit: 60 },
      { key: "applicantRepName", label: "届出者 代表者氏名", required: false, xsd: "APPLICAT_REP_NAME", limit: 100 },
      { key: "applicantAddress1", label: "届出者 所在地1", required: false, xsd: "APPLICAT_ADDRESS1", limit: 120 },
      { key: "applicantAddress2", label: "届出者 所在地2", required: false, xsd: "APPLICAT_ADDRESS2", limit: 120 },
      { key: "applicantPersonName", label: "届出担当者 氏名", required: false, xsd: "APPLICAT_PERSON_NAME", limit: 200 },
      { key: "applicantPersonTitle", label: "届出担当者 所属", required: false, xsd: "APPLICAT_PERSON_TITLE", limit: 200 },
      { key: "applicantTel", label: "電話番号", required: false, xsd: "APPLICAT_TELNUM", limit: 50 },
      { key: "faxOrEmail", label: "FAX番号又はメールアドレス", required: false, xsd: "FAXNUMBER", limit: 50 },
      { key: "foreignSponsorName", label: "海外依頼者等 名称（邦文）", required: false, xsd: "FOREIGN_SPONSOR_NAME", limit: 120 },
      { key: "foreignSponsorRepName", label: "海外依頼者等 代表者氏名（邦文）", required: false, xsd: "FOREIGN_SPONSOR_REP_NAME", limit: 100 },
      { key: "foreignAddress1", label: "海外依頼者等 所在地1（邦文）", required: false, xsd: "FOREIGN_SPONSOR_ADDRESS1", limit: 120 },
      { key: "foreignNameForeignLang", label: "海外依頼者等 名称（外国語）", required: false, xsd: "FOREIGN_NAME_FRGNLNG", limit: 120 },
      { key: "foreignAddressForeignLang", label: "海外依頼者等 所在地（外国語）", required: false, xsd: "FOREIGN_ADDRESS1_FRGNLNG", limit: 120 },
    ],
  },
  {
    id: "doctors",
    title: "医師情報",
    icon: Stethoscope,
    list: "Doctor Events",
    description: "責任医師・分担医師の追加、削除、氏名変更をイベント行として記録します。",
    mode: "doctorTable",
  },
  {
    id: "organizations",
    title: "関係者・委託先",
    icon: Building2,
    list: "Related Organizations",
    description: "届出者、CRO、SMO、費用負担者などを役割別に管理します。",
    mode: "organizationTable",
  },
  {
    id: "references",
    title: "参照届出",
    icon: FileText,
    list: "Referenced Notifications",
    description: "B.6の参照する治験届出情報を複数行で管理します。",
    mode: "referencesTable",
  },
  {
    id: "gaiji",
    title: "外字・表記",
    icon: Languages,
    list: "Gaiji Mappings",
    description: "原表記と届出用表記、置換理由、説明資料化の状態を管理します。",
    mode: "gaijiTable",
  },
  {
    id: "history",
    title: "履歴・監査",
    icon: History,
    list: "Audit Events",
    description: "変更履歴、順序番号イベント、承認、電子署名、旧版トレースを確認します。",
    mode: "history",
  },
];

export const workflowSteps = [
  { id: "draft", title: "起票", status: "done", owner: "薬事担当", note: "入力データ作成済み" },
  { id: "review", title: "レビュー", status: "current", owner: "レビュー担当", note: "外字と変更区分を確認中" },
  { id: "approve", title: "承認", status: "waiting", owner: "承認者", note: "電子署名待ち" },
  { id: "preview", title: "PDF確認", status: "locked", owner: "起票者", note: "承認後に閲覧可能" },
  { id: "export", title: "出力", status: "locked", owner: "システム", note: "PDF/XML生成" },
];
